version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - PYTHONPATH=/app
    command: python src/app.py  # Use Flask development server for local development 